import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/topnav";
import NavLinks from "@/components/NavLinks";


const notoserif = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoserif.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TopNav />
        <NavLinks />
        {children}
      </body>
    </html>
  );
}
